PromotionsWebApp/Controllers/DocumentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using PromotionsWebApp.Domain.Abstract;
using PromotionsWebApp.Domain.Entities;
using PromotionsWebApp.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static PromotionsWebApp.ViewComponents.UploadDocumentsViewComponent;

namespace PromotionsWebApp.Controllers
{
    public class DocumentController : BaseController
    {
        public DocumentController(IServiceScopeFactory factory) : base(factory)
        {

        }

        [HttpGet]
        public async Task<JsonResult> GetDocument([FromQuery] int docId)
        {
            try
            {
                var doc = await _documentRepo.GetSingle(x => x.Id == docId);
                if (doc != null)
                {
                    var content = doc.Content;
                    return Json(content);
                }
            }
            catch (Exception ex)
            {
                return Json(false);
            }
            return Json(true);
        }

        [HttpGet]
        public async Task<JsonResult> Delete([FromQuery] int docId)
        {
            try
            {
                var doc = await _documentRepo.GetSingle(x => x.Id == docId);
                if (doc != null)
                    await _documentRepo.Delete(doc.Id);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
            return Json(true);
        }

        [HttpPost]
        public async Task<IActionResult> UploadDocument(UploadDocumentsViewModel model)
        {
            int staffId = 0;
            try
            {
                var supportDoc = await _supportDocumentsRepo.GetSingle(model.SupportingsDocumentId);
                if (supportDoc != null)
                {
                    staffId = supportDoc.StaffId;
                    switch (model.UploadType)
                    {
                        case UploadTypeEnum.CV:
                            supportDoc.CV = new Document
                            {
                                FileName = "Staff_" + staffId + "_CV",
                                Content = await model.UploadFile.GetBytes(),
                                SupportingDocumentsId = model.SupportingsDocumentId
                            };
                            await _documentRepo.Add(supportDoc.CV);
                            supportDoc.CVId = supportDoc.CV.Id;
                            break;
                        case UploadTypeEnum.ID:
                            supportDoc.IdentityDocument = new Document
                            {
                                FileName = "Staff_" + staffId + "_ID",
                                Content = await model.UploadFile.GetBytes(),
                                SupportingDocumentsId = model.SupportingsDocumentId
                            };
                            await _documentRepo.Add(supportDoc.IdentityDocument);
                            supportDoc.IdentityDocumentId = supportDoc.IdentityDocument.Id;
                            break;
                        case UploadTypeEnum.StudentEval:
                            supportDoc.StudentEvalForm = new Document
                            {
                                FileName = "Staff_" + staffId + "_SE",
                                Content = await model.UploadFile.GetBytes(),
                                SupportingDocumentsId = model.SupportingsDocumentId
                            };
                            await _documentRepo.Add(supportDoc.StudentEvalForm);
                            supportDoc.StudentEvalFormId = supportDoc.StudentEvalForm.Id;
                            break;
                        case UploadTypeEnum.PeerEval:
                            supportDoc.PeerEvalForm = new Document
                            {
                                FileName = "Staff_" + staffId + "_PE",
                                Content = await model.UploadFile.GetBytes(),
                                SupportingDocumentsId = model.SupportingsDocumentId
                            };
                            await _documentRepo.Add(supportDoc.PeerEvalForm);
                            supportDoc.PeerEvalFormId = supportDoc.PeerEvalForm.Id;
                            break;
                        case UploadTypeEnum.CommunityService:
                            supportDoc.CommunityServiceForm = new Document
                            {
                                FileName = "Staff_" + staffId + "_CS",
                                Content = await model.UploadFile.GetBytes(),
                                SupportingDocumentsId = model.SupportingsDocumentId
                            };
                            await _documentRepo.Add(supportDoc.CommunityServiceForm);
                            supportDoc.CommunityServiceFormId = supportDoc.CommunityServiceForm.Id;
                            break;
                        case UploadTypeEnum.ScholarshipInTeaching:
                            supportDoc.ScholarshipInTeachingForm = new Document
                            {
                                FileName = "Staff_" + staffId + "_ST",
                                Content = await model.UploadFile.GetBytes(),
                                SupportingDocumentsId = model.SupportingsDocumentId
                            };
                            await _documentRepo.Add(supportDoc.ScholarshipInTeachingForm);
                            supportDoc.ScholarshipInTeachingFormId = supportDoc.ScholarshipInTeachingForm.Id;
                            break;
                    }
                }

                TempData["Toast"] = "Document has been successfuly upload";
            }
            catch (Exception ex)
            {
                return RedirectToAction("Profile", new { staffId = staffId });
            }
            return RedirectToAction("Profile", new { staffId = staffId });
        }
    }
}

PromotionsWebApp/Views/Shared/Components/UploadDocuments/Default.cshtml
@model PromotionsWebApp.ViewComponents.UploadDocumentsViewComponent.UploadDocumentsViewModel
@using PromotionsWebApp.Domain.Abstract

@*Support Document Add Modal*@

@{ 
    var headerText = "";
    var modalName = "";
    switch(Model.UploadType)
    {
        case UploadTypeEnum.CV:
            headerText = "Curriculum Vitae";
            modalName = "cvModal";
            break;
        case UploadTypeEnum.ID:
            headerText = "Identity Document";
            modalName = "idModal";
            break;
        case UploadTypeEnum.StudentEval:
            headerText = "Student Evalution Forms";
            modalName = "seModal";
            break;
        case UploadTypeEnum.PeerEval:
            headerText = "Peer Evaluation Forms";
            modalName = "peModal";
            break;
        case UploadTypeEnum.CommunityService:
            headerText = "Community Service Forms";
            modalName = "csModal";
            break;
        case UploadTypeEnum.ScholarshipInTeaching:
            headerText = "Scholarship in Teaching Forms";
            modalName = "stModal";
            break;
    }
}
<a href="#@modalName" class="tooltipped modal-trigger" id="uploadSupportBtn" data-position="top" data-tooltip="Upload Support Document">Upload</a>
<div id="@modalName" class="modal grey lighten-5">
    <form id="supportForm" asp-action="UploadSupportDocument" asp-controller="Document" method="post" role="form" enctype='multipart/form-data'>
        <input type="hidden" asp-for="SupportingsDocumentId" id="docId" />
        <input type="hidden" asp-for="UploadType" />
        <div class="modal-content">
            <h2 class="center-align">Upload @headerText</h2>
            <div class="row">
                <div class="row">
                    <div class="input-field col s8 offset-s2">
                        <Label class="active">Upload Document</Label><br/>
                        <input type="file" accept="application/pdf" class="validate" asp-for="UploadFile" required />
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <div class="input-field col s8 offset-s2">
                <a class="btn modal-close waves-effect waves-light btn-large red lighten-1">
                    <span class="material-icons md-dark md-24 matIcon">
                        cancel
                    </span>
                    <span class="black-text">Cancel</span>
                </a>
                <button type="submit" id="submitEducationBtn" class="btn waves-effect waves-light btn-large green lighten-1">
                    <span class="material-icons md-dark md-24 matIcon">
                        send
                    </span>
                    <span class="black-text">Submit</span>
                </button>
            </div>
        </div>
    </form>
</div>